language: python
python:
- 2.6
- 2.7
- 3.3

install:
- pip install -U pip setuptools pytest
- pip install --use-mirrors \
    `python -c 'from setup import META; print(" ".join(META["extras_require"]["testing"] + META["install_requires"]))'`

script: make test

notifications:
  irc: "irc.freenode.net#tiddlyweb"
